# Site settings
title: *folio
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  posts:
    output: true
    permalink: /posts/:path/
  research:
    output: true
    permalink: /research/:path/
  projects:
    output: true
    permalink: /projects/:path/
  other:
    output: true
    permalink: /xother/:path/


